# We're adding an additional namespace
# around the :numbers namespace. This is
# to show that you can infinitely nest
# namespaces, but I advise against going
# deeper than 2 namespaces and one task.
namespace :group do
  namespace :numbers do
    desc 'Will display "first"'
    task :first do
      puts '** First **'
    end

    desc 'Will display "second"'
    task :second => :first do
      puts '** Second **'
    end
  end
end